### ISSUE TITLE
Setningsnivå: "Gutta"

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#13]
"Gutta" (istedenfor "guttene") brukes i en del sammenhenger, og ofte i tweets som ellers ikke har noen klare dialektmarkører. "Gutta" er jo ikke en bøyningsform i Bokmålsordboka, men gir som dere ser på bildet treff på uttrykket "de store gutta". 

Jeg tenker også på "gutta" mer som et slags uttrykk enn en bøyningsform, da det ofte brukes i settinger hvor det ville vært unaturlig å bruke "guttene", f.eks. når håndballandslaget for herrer omtales som "håndballgutta".  På den annen side finnes det kanskje dialekter hvor "gutta" ikke brukes, så sånn sett er det kanskje en dialektmarkør?

Tenker dere at "gutta" (alene) kvalifiserer til "dialectal"?

![image](https://user-images.githubusercontent.com/58046013/139596322-a6c9574d-bce1-4c2a-a9ee-8272ab62870c.png)

**Comment by marieef** [comment]
@Tyriflis

**Comment by Tyriflis** [comment]
Hmm godt spørsmål! Vi kunne eventuelt markert det som "marked" gitt den marginale plassen i ordboka, og derfor tatt med setningen som inneholder det, samtidig som det kan godt hende at personen som skriver setningen ikke mener å la så mye av sin egen "dialekt" skinne igjennom?

**Comment by marieef** [comment]
Etter å ha diskutert det litt mer med deg @Tyriflis, tror jeg vi landet på at man kan vise litt skjønn og at setningen ikke nødvendigvis klassifiseres som "dialectal" hvis det ikke finnes noen andre dialektmarkører der. Synes det kan gi mening å ha det som "marked" i ordnivåannotasjonen :)
