### ISSUE TITLE
Ordnivå: "kronasjer"

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#14]
Du trenger ikke betale masse **kronasjer** på Onlyfans for å se pupper og lår , enkefru Sigvaldsen sender gladelig bilder tell deg i posten mot ei halv ei.

Gir det mening å markere "kronasjer" som lexical? Det finnes ikke i bokmålsordboka. I [NAOB](https://naob.no/ordbok/kronasje) står det at ordet er laget av "krone" og endelsen "-asje" (fra fransk). 
Blir det da litt feil å kalle det lexical, eller skal jeg forholde meg helt strengt til at ordet ikke finnes i bokmålsordboka?

**Comment by marieef** [comment]
@Tyriflis

**Comment by Tyriflis** [comment]
Godt spørsmål! Det handler kanskje litt om hvor mye skjønn vi vil utvise. På en side vil vi være strenge, men samtidig er kanskje ikke dette egentlig den type ord vi er så interesserte i. Ordene som finnes i NAOB vil i stor grad ikke være knyttet til dialekt, så sånn sett burde vi kunne bruke den også, men vi kan ikke bruke Norsk Ordbok på samme måte for nynorsk. Jeg tror ikke egentlig vi tjener så mye på å ta med dette ordet?
