### ISSUE TITLE
Ordnivå: tanker -> tænker?

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#15]
"Og du fortjener alt godt vettu . Heia på dæ og dine **tænker**"

Jeg kan ikke skjønne noe annet enn at det dreier seg om "tanker" og har derfor tenkt at det er vowel shift, men synes denne endringen fra "a" til "æ" virker litt ukjent.. 

Noen som forstår dette på en annen måte?

**Comment by Tyriflis** [comment]
Enig i at den er litt rar her, men tror allikevel det er det beste alternativet!
