### ISSUE TITLE
typo i annotations-instruks

### ISSUE THREAD

**Issue by holten** [jerbarnes/nordial#2]
[https://github.com/jerbarnes/nordial/tree/main/v1.1/annotation_project/README.md](https://github.com/jerbarnes/nordial/tree/main/v1.1/annotation_project/README.md)
Her står det akkurat no:
2. Nynorsk: Twittermeldingen inneholder ikke dialektord, og virker ment å være på normert bokmål.

Eg gjer framlegg om endring til dette:
2. Nynorsk: Twittermeldingen inneholder ikke dialektord, og virker ment å være på normert nynorsk.

**Comment by jerbarnes** [comment]
Takk for at du sa ifra. Har fikset skrivefeilen nå.
