### ISSUE TITLE
Apokope

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#20]
"æ **sett** te æ bli bekka så tar æ affære"

Kan bortfall av "-er"-endelse i presens ("sett") kalles apokope, eller gjelder det kun når f.eks. "å kaste" blir "å kast" i infinitiv?
Mulig at det bare er vokalendring det er snakk om i tilfelle med "sett", og kanskje shortening (hvis man tar utgangspunkt i "å sitje" - "sit").

**Comment by Tyriflis** [comment]
Som du nevner er det kanskje ikke apokope her siden det kommer fra sitje, men i utgangspunktet virker det som vi kan bruke apokope i presens også, men da har det alltid(?) også skjedd bortfall av -r, for at apokopen skal kunne skje. 

Fra Store Norske Leksikon:

Endingskonsonanten -r fell bort i presens av svake e-verb, som ofte også får apokope av vokalen, jamfør setningane «eg kjennj han ikkje» og «det høv ikkje i dag!».

https://snl.no/dialekter_i_Nordland

(Men siden "sitje" ikke er et e-verb, så holdet det nok med vokalendring i dette tilfellet)

**Comment by marieef** [comment]
Ok, skjønner. Takk!
