### ISSUE TITLE
Pronomenet "hen"

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#21]
Gir det mening å markere dette med pron_subj/pron_obj? Det er jo ikke et dialektord, men et uoffisielt norsk kjønnsnøytralt pronomen. Tenkte også på "Lexical", men det skal vel ikke brukes på funksjonsord.

**Comment by Tyriflis** [comment]
Jeg tenker at så lenge en tvitring er markert med dialekt, så er pronomendistribusjonen interessant. Vi vil jo potensielt også få med noen andre tilsynelatende normerte former også, og i verste fall så kan vi si noe om bruken av "hen" i forskjellige dialekter.
