### ISSUE TITLE
Oppsamling av noen spørsmål

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#23]
- Kjenner noen av dere til ordet "sekju" i setningen under, i det minste hvilken ordklasse det er? Jeg fant en kilde hvor jeg fikk inntrykk av at det kan bety "saken", men er langt fra sikker på at det stemmer. 

_"Jajamen, mørbrad er **sekju** gett, veldig godt på grill å, mørbrad å høyrygg å entrøkå er nam nammenam"_

- Høres det greit ut å markere adjektiv med endelse "-lig" eller "-leg" med vowel shift hvis den varianten som forekommer virker utypisk i sin kontekst?

- Lurer på det samme (vowel shift) om determinativer som "en"/"ein". Men det er kanskje bedre å forholde seg til at vi ser bort fra funksjonsord så lenge de ikke er eksplisitt dialektale?

- Varianter av "i morgen" som "imårå"/ "imårra" - gir det mening å markere disse som noe annet enn functional og evt vowel shift?

- "kem" ("hvem" på trøndersk) er selvfølgelig functional, men er det riktig å tagge med h_v?

**Comment by Tyriflis** [comment]
Jeg kjenner ikke til ordet, men om det kommer fra "sak", så er det kanskje så vanskelig å kjenne igjen, at du kan markere det som "lexical"? Vil tro at det er et gradsadverb her? 

Vowel shift bør nok egentlig begrenses til innad i lemmaene, ikke i endelser, men så har vi dette problemet med avledningsendelser som ikke egentlig dekkes av noe annet. Kanskje det er like greit å gjøre det.

Ja, stemmer, vi unngår vowel shift på funksjonsord siden de ofte er så vanskelige å fastslå.

Når det kommer til adverbene beveger vi oss kanskje bort fra hovedtanken med functional. Jeg tenker at mårå og mårra er fine eksempler på vowel shift.

Stemmer! Kem skal også ha h_v.

**Comment by marieef** [comment]
Takk for alle svar, det var oppklarende :)
Da går jeg for å markere vowelshift i avledningsendelser.
