### ISSUE TITLE
Engelske lånord

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#26]
Tror vi snakket om å ignorere alle engelske lånord på møtet vi hadde i januar. Mente vi da helt "rene" engelske ord som i 4, eller alle tilfellene 1 - 4?
Min intuisjon får litt lyst til å bruke 'lexical' i 1, 2 og 3, men ignorere "lowkey" i 4 hvor det ikke er snakk om noen form for bøyning eller fornorsket skrivemåte, men korriger meg hvis det blir inkonsekvent og dumt.

1) æ vil vite ka faen han skreiv på den veggen får sjela mi førlat kroppen min og nu må æ hør meldinga ? ? ? ? **Fakk** ass

2) **plis** , æ har ikje lange veien å gå te havna for å drukne mæskjøl , dont push me

3) satt og va klar for å **cringe** som faen av talen te Sivert men det va jo faktisk ganske bra

4) æ sett å cringe over det faktum at æ **lowkey** får heimlengsel

**Comment by Tyriflis** [comment]
Jeg synes det er en fin beslutning!

**Comment by marieef** [comment]
Så bra!
