### ISSUE TITLE
Bruk av conjugation-taggen

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#5]
I noen tilfeller er jeg litt usikker på om jeg skal bruke denne kategorien. 

1) Vil man annotere ord som omfattes av present_marker_deletion-taggen med conjugation-taggen i tillegg?

2) Vil alle andre unormerte verbformer markeres som conjugation? Jeg skjønner at det gjelder eksempelet med "skrivi" vs. "skrive", men blir litt usikker i andre tilfeller hvor verbformen er unormert uten at det dreier seg om en unormert _endelse_. (Kan gi et eksempel her hvis det er uklart hva jeg mener.)

**Comment by Tyriflis** [comment]
1. Jeg tenker at det ikke er nødvendig å markere med både present_marker_deletion og conjugation, siden det alltid vil være tilfellet.
2. Godt poeng! Hvis det ikke er endelsen som er unormert så burde vi nok ikke bruke den. Da burde variasjonen i verbet plukkes opp av en annen tag, hvis mulig.

**Comment by marieef** [comment]
1. Ok, det gir mening :) 
2. Hvis det er ok å være litt mer spesifikk, mener jeg f.eks. når "sku" brukes istedenfor "skulle" i preteritum, uten at det er brukt på en måte som gjør at det kan markeres som contraction. Her er det altså ikke lagt til noen unormert endelse, så derfor var jeg usikker på om conjugation kan brukes. Ellers tenkte jeg at functional-taggen kanskje kan brukes, for modale hjelpeverb regnes vel som funksjonsord? @Tyriflis

**Comment by Tyriflis** [comment]
2.  Dette minner kanskje mest om det vi ville markere i present_marker_deletion, bare at det ikke er presens. Samtidig så tror jeg ikke det er veldig frekvent, så kanskje å markere det som functional, som du nevner, er det beste, ja!
