### ISSUE TITLE
Enclitic pronouns

### ISSUE THREAD

**Issue by marieef** [jerbarnes/nordial#8]
Jeg klarer ikke å finne ut av hva som menes med "enclitic pronouns", som er nevnt under "contraction" i retningslinjene. 
Har noen en forklaring og et eksempel på dette?

**Comment by Tyriflis** [comment]
Her er det snakk om tilfeller som "Kjenner'u'a?" eller "Ser'u'røm?" Hvor "u" er enklitisk form av "du", "a" av "hun", "røm" av "døm" av "dem" osv. 

Pass på at disse kan ligne på "dem_pron", men forskjellen er at de enklitiske pronomene bevarer sine selvstendige semantiske roller.

**Comment by Tyriflis** [comment]
Spesifisering: Relasjonen mellom "døm" og "dem" er altså ikke enklitisk, det var bare for å vise rekka hele veien til bokmål.
